import os
import resend
from dotenv import load_dotenv

# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

RESEND_API_KEY = os.getenv("RESEND_API_KEY")
RECEIVER_EMAIL = os.getenv("ALERT_RECEIVER_EMAIL")

# Configure Resend
if RESEND_API_KEY:
    resend.api_key = RESEND_API_KEY


# ============================================================
# SEND BUSINESS ALERT EMAIL
# ============================================================

def send_alert_email(
    incident_id,
    incident_date,
    metrics,
    severity,
    ai_analysis
):
    """
    Send a business anomaly alert email using Resend.
    """

    # --------------------------------------------------------
    # Check API key
    # --------------------------------------------------------

    if not RESEND_API_KEY:
        print("❌ RESEND_API_KEY not found in .env")
        return False

    # --------------------------------------------------------
    # Check receiver email
    # --------------------------------------------------------

    if not RECEIVER_EMAIL:
        print("❌ ALERT_RECEIVER_EMAIL not found in .env")
        return False

    # --------------------------------------------------------
    # Email subject
    # --------------------------------------------------------

    subject = (
        f"🚨 {severity} Business Anomaly Alert - "
        f"{incident_id}"
    )

    # --------------------------------------------------------
    # Email body
    # --------------------------------------------------------

    html_body = f"""
    <!DOCTYPE html>

    <html>

    <head>

        <meta charset="UTF-8">

        <title>
            Business Anomaly Alert
        </title>

    </head>

    <body>

        <h2>
            🚨 Business Anomaly Alert
        </h2>

        <hr>

        <h3>
            📊 Incident Details
        </h3>

        <p>
            <strong>Incident ID:</strong>
            {incident_id}
        </p>

        <p>
            <strong>Date:</strong>
            {incident_date}
        </p>

        <p>
            <strong>Metrics:</strong>
            {metrics}
        </p>

        <p>
            <strong>Severity:</strong>
            {severity}
        </p>

        <hr>

        <h3>
            🤖 AI Business Analysis
        </h3>

        <div style="
            background-color: #f5f5f5;
            padding: 15px;
            border-radius: 8px;
            font-family: Arial, sans-serif;
            white-space: pre-wrap;
        ">
{ai_analysis}
        </div>

        <hr>

        <p>
            This alert was automatically generated by:
        </p>

        <p>
            <strong>
                AI Business Anomaly Detection & Alert Agent
            </strong>
        </p>

    </body>

    </html>
    """

    # --------------------------------------------------------
    # Send email
    # --------------------------------------------------------

    try:

        response = resend.Emails.send(
            {
                "from": (
                    "AI Business Anomaly Agent "
                    "<onboarding@resend.dev>"
                ),
                "to": [RECEIVER_EMAIL],
                "subject": subject,
                "html": html_body
            }
        )

        print("✅ Alert email sent successfully!")

        print(
            f"📧 Email ID: {response.get('id')}"
        )

        return True

    except Exception as e:

        print("❌ Failed to send alert email.")

        print(
            f"Error: {e}"
        )

        return False


# ============================================================
# TEST EMAIL
# ============================================================

if __name__ == "__main__":

    print(
        "\n📧 Testing business alert email...\n"
    )

    test_result = send_alert_email(

        incident_id="INC-TEST-001",

        incident_date="2026-08-13",

        metrics="Revenue",

        severity="HIGH",

        ai_analysis="""
BUSINESS INSIGHT:
Revenue increased significantly compared to the baseline.

POSSIBLE CAUSE:
Possible increase in demand or successful marketing activity.

BUSINESS IMPACT:
The increase may indicate a positive business opportunity.

RECOMMENDED ACTION:
Investigate the reason for the increase and monitor future revenue.
"""
    )

    print()

    if test_result:

        print(
            "🎉 Email alert test completed successfully!"
        )

    else:

        print(
            "❌ Email alert test failed."
        )